### ISSUE TITLE
Animations play in fast forward after running in background tab

### ISSUE THREAD

**Issue by charlestudor** [replit/kaboom#20] opened 2021-04-16 16:53 UTC
When a scene is left running in another browser tab, and that tab is reopened, sprites that had active animations running play them in fast-forward until they are fully caught up.

This issue seems to occur in different browsers (tested Firefox and Chrome) and when using either the loadSprite or loadAseprite functions to load the sprite.

I have some code to reproduce if that would be useful.

Many Thanks!

**Comment by mamamia5x** [comment] 2021-04-16 17:03
I believe this issue isn't kaboom's fault. I've had this happen to me on many browser games. The game doesn't fully run in the background, so when you go back to the site, it needs to catch up to where it's supposed to be. I don't know if kaboom will try to fix this issue, because it's not really a kaboom issue, it's the browsers. Idk if there is a workaround to it, maybe webworkers?

**Comment by charlestudor** [comment] 2021-04-16 17:10
Thanks for the quick response!. Yep I've seen that before as well, it makes sense if it's too much of a pain to workaround.

Perhaps another option would be using the Page Visibility API to pause animations (or more) when the page loses focus? Not sure if that would cause unforseen problems though.

**Comment by slmjkdbtl** [comment] 2021-04-16 17:11
Yeah I've noticed this sometime and looks like a browser thing with `requestAnimationFrame`, I'll look into the page visibility API and see if it can solve!

**Comment by mamamia5x** [comment] 2021-04-16 17:22
I've seen Web Workers work. These Web Workers continue to run in the background, but it only runs a whole file, not just functions. 

There is also background tasks, but I can't say much about it.
### Web Workers
* https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers
* https://www.w3schools.com/html/html5_webworkers.asp

### Background Tasks
* https://developer.mozilla.org/en-US/docs/Web/API/Background_Tasks_API
* https://www.luigicolella.it/blog/how-to-use-js-background-tasks-api

**Comment by aaronjewell** [comment] 2021-04-16 18:47
You might also be able to tie into the page visibility API and set the kaboom.debug.timeScale to zero when the tab is switched away, and scale it back when it's visible again. I haven't tried it out though.

**Comment by mamamia5x** [comment] 2021-04-16 18:52
Oh yeah, I never thought about that. This would be a good fix for the user

**Comment by slmjkdbtl** [comment] 2021-04-16 20:11
the root cause seems to be a surge of `dt` when the tab is hidden and switch back again, `requestAnimationFrame` seem to be paused, but its timer seems to keep going on which causes the surge, eecfc3c should fixed this

**Comment by charlestudor** [comment] 2021-04-16 21:32
Looks like that's fixed it, nice work!

I suppose this might have ramifications if someone wanted to make an "idle" style game where you amass points whilst afk or on another window. Not sure if that's an issue or not..

**Comment by slmjkdbtl** [comment] 2021-04-16 21:36
Good to hear! 

Hmm I think in this case they might have to rely on web workers and stuff, the browser won't run the main `requestAnimationFrame` loop at all when the tab is hidden.

If this specific issue is resolved I'm going to close it, feel free to reopen if there's unsolved cases.

**Closed by slmjkdbtl** 2021-04-16 21:36 UTC
Labels: bug

**Comment by mamamia5x** [comment] 2021-04-19 12:28
A little late for the response, but another workaround could be to pause the game when off screen.
