### ISSUE TITLE
Sometime "Body" objects fall through "Solid" objects if dropped down. 

### ISSUE THREAD

**Issue by TheMiniDriver** [replit/kaboom#86] opened 2021-06-17 08:44 UTC
[kaboom-solid-bug.zip](https://github.com/replit/kaboom/files/6668700/kaboom-solid-bug.zip)
See attached example project. 

 Basically, object marked with "body" sometimes fall through "solid" objects. 
You can see in this demo that things fall through the floor occasionally.
 It also logs in the console whenever it happens

**Comment by sixhobbits** [comment] 2021-06-17 08:58
or here is a repl demonstrating the issue

https://replit.com/@ritza/kaboom-solid-bug

https://kaboom-solid-bug.ritza.repl.co/

**Comment by slmjkdbtl** [comment] 2021-06-17 16:17
i can't repro on my end but i think it's caused by: right now physics resolution is checking if 2 objects are colliding, if yes push one out of another, on lower frame rates `dt` is high so when an object is falling it might not have a frame when the 2 objects are actually colliding (happens more when the objects are small / thin), was planning to move to another system that'll solve this problem e.g. checks on `move()` and uses the directional vector

**Comment by sixhobbits** [comment] 2021-06-17 18:58
Oh interesting - here's a gif from the above link for me - it happens around 1 in every 10 falls I think.

https://cln.sh/xgUH2h

Might be a latency thing too? - I'm in Europe and @TheMiniDriver is in South Africa - I know we also had some issues with PyGame that weren't as apparent from the US.

**Comment by slmjkdbtl** [comment] 2021-06-17 19:50
Network latency shouldn't be a thing as everything is on the client. I wonder what's your fps are (`k.debug.fps()`), if a simple scene like this is causing fps <= 58 means something is terribly wrong

**Comment by TheMiniDriver** [comment] 2021-06-18 06:44
Thanks for the insight - I added in the fps measure when it falls through. It seems to be around 59 / 60 
I noticed that it seems to fall through a lot more when the window is on an external monitor, as opposed to my laptop's screen. I am using a low end Dell external, not sure if that would make any difference? 

![Screenshot 2021-06-18 at 8 41 44 AM](https://user-images.githubusercontent.com/4689280/122518253-4379a880-d011-11eb-8823-561141095338.png)

**Comment by fraigo** [comment] 2021-06-30 14:17
It looks like there it's movement/velocity related. If the velocity is higher (eg: more gravity or fewer animation frames) it tends to bypass the solid object. I've made a new example that is more notorious (especially on high CPU usage or low CPU speed) 
https://replit.com/@FranciscoIgor/kaboom-solid-bug
You will note some falling objects through the red wall and also through the green wall 
My guess is the collision algorithm only checking position by frame, some frames could not detect a collision if the object is 'passing through'  in that frame

**Comment by Svoig** [comment] 2021-07-09 16:35
I've noticed this too. I'm working on a game with a large map (using `createLevel`), and my player and enemies frequently fall through the ground (presumably due to high CPU utilization from so many tiles to check collisions against). My player also clips through walls if moving fast enough. I've tried setting a max velocity, and that helps a bit.

**Comment by slmjkdbtl** [comment] 2021-07-09 16:38
@Svoig There's no optimizations for large amount of collision objects yet. One trick you can do now is turn off `solid` attrib of tiles if it's far away from the player so it'll not partake in the check
```js
action("tile", (t) => {
    t.solid = player.pos.dist(btpos) <= 32; // arbitrary distance based on you tile size
});
```

**Comment by MortyHub** [comment] 2021-08-30 22:49
> [kaboom-solid-bug.zip](https://github.com/replit/kaboom/files/6668700/kaboom-solid-bug.zip)
> See attached example project.
> 
> Basically, object marked with "body" sometimes fall through "solid" objects.
> You can see in this demo that things fall through the floor occasionally.
> It also logs in the console whenever it happens

So basically i fixed it by doing this:

player.collides('dirt', ()=>{
	player.move(0,-200)
})

when it collides with the object under the grass as i call it, it moves the player up so that they dont just fall through, if you pc is lagging a lot then it might not work.

**Comment by slmjkdbtl** [comment] 2021-11-02 00:03
Fixed with 2000 continuous collision resolution.

**Closed by slmjkdbtl** 2021-11-02 00:03 UTC
Labels: bug
