### ISSUE TITLE
Prevent blue error screen

### ISSUE THREAD

**Issue by peratik** [replit/kaboom#773] opened 2023-10-20 10:01 UTC
![image](https://github.com/replit/kaboom/assets/6568353/f5ce0155-c208-48c1-a95d-a25805a0caf7)

Hi, How can prevent blue error screen?

**Comment by slmjkdbtl** [comment] 2023-10-20 13:29
Normally blue screen error means there's an error that's unrecoverable and should be fixed, but this one looks like a bug where someplace threw a string instead of an `Error`. Is there any console output?

**Comment by peratik** [comment] 2023-10-22 15:38
the error is not related tokaboom codes.

**Comment by peratik** [comment] 2023-10-23 07:00
Doesn't `onError` work for this?

**Comment by slmjkdbtl** [comment] 2023-10-23 11:14
`onError` adds your own error handler but doesn't replace this error screen. If the error is unrelated to kaboom then it's a bug, it's fixed in `v3000.1.7`, you can try update kaboom to the latest version

**Comment by peratik** [comment] 2023-10-23 11:18
Isn't `v3000.1.13` the latest version?

**Comment by slmjkdbtl** [comment] 2023-10-23 11:25
You're already on v3000.1.13 and getting error screen from non-Kaboom Error? That's weird. What is the error, can you share the console output?

**Comment by peratik** [comment] 2023-10-23 12:57
We use kaboom canvas inside an iframe. It may be a reason to that if there is already a fix. 
Error message in the parent iframe display inside kaboom that exists in child iframe.

**Comment by slmjkdbtl** [comment] 2023-10-23 12:58
Do you have an example I can reproduce? Also what is the error message in the console output?

**Comment by peratik** [comment] 2023-10-23 13:12
This is an example:

https://coffee-adria-35.tiiny.site/

Click on the button.

**Comment by slmjkdbtl** [comment] 2023-10-23 13:28
Oh sorry I got it mixed up, the fix is not yet published, will be published to the next version soon

**Comment by peratik** [comment] 2023-10-27 09:55
Hi, Any ETA for releasing the next version?

**Comment by slmjkdbtl** [comment] 2023-11-07 14:59
v3000.0.15 is released, which includes the fix

**Closed by slmjkdbtl** 2023-11-07 14:59 UTC
